source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '12.0'

target 'HQListView_Example' do
  pod 'StockListView', :path => '../'
  pod 'MJRefresh'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'SwiftLint', '0.35.0', :configurations => ['Debug']
  pod 'SwiftFormat/CLI', '0.49.4', :configurations => ['Debug']
  target 'HQListView_Tests' do
    inherit! :search_paths

    
  end
end
